import Head from "next/head";
import Header from "../components/Header";
import { useState, useEffect } from "react";

export default function Home() {
  const [podcasts, setPodcasts] = useState([]);

  useEffect(() => {
    getPodcasts();
  }, []);

  const getPodcasts = async () => {
    const res = await fetch(
      "https://itunes.apple.com/us/rss/toppodcasts/limit=100/genre=1310/json"
    );
    const finalRes = await res.json();
    setPodcasts(finalRes.feed.entry);
    console.log(finalRes.feed.entry);
  };

  return (
    <>
      <Head>
        <title>Prueba Matrix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h2>Hola mundo</h2>
      {podcasts.map((podcast) => (
        <p key={podcast.id.attributes["im:id"]}>{podcast.title.label}</p>
      ))}
    </>
  );
}
