import Head from "next/head";
import Header from "../components/Header";
import PodcastCard from "../components/PodcastCard";
import { useState, useEffect } from "react";

export default function Home() {
  const [podcasts, setPodcasts] = useState([]);

  useEffect(() => {
    getPodcasts();
  }, []);

  const getPodcasts = async () => {
    const res = await fetch(
      "https://itunes.apple.com/us/rss/toppodcasts/limit=100/genre=1310/json"
    );
    const finalRes = await res.json();
    setPodcasts(finalRes.feed.entry);
    console.log(finalRes.feed.entry);
  };

  return (
    <>
      <Head>
        <title>Prueba Matrix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container w-5/6 mx-auto mb-8">
        <div className="grid grid-cols-4 gap-x-4 gap-y-24">
          {podcasts.map((podcast) => (
            <PodcastCard
              key={podcast.id.attributes["im:id"]}
              id={podcast.id.attributes["im:id"]}
              title={podcast.title.label}
              img={podcast["im:image"][2].label}
              author={podcast["im:artist"].label}
            />
          ))}
        </div>
      </div>
    </>
  );
}
